config/routes.rb
Rails.application.routes.draw do

resources :charges, only: [:new, :create] 
  put 'downgrade_user' => "charges#downgrade_user"
  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end

  devise_for :users
  get 'about' => 'welcome#about'

  root to: 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :wikis, through: :collaborators
  has_many :collaborators
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def admin?
    role == "admin"
  end

  def premium?
    role == "premium"
  end

  def can_make_private_wiki?
    premium? || admin?
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :users, through: :collaborators
  has_many :collaborators
  
  default_scope {order('created_at ASC')}
  #scope :visible_to, -> (user) {where(private: true) }

  def public?
    private == false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
  
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "BigMoney Membership - #{current_user.name}",
     amount: Amount.default
   }
  end

  def create
    # Creates a Stripe Customer object for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken])

    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, #Note -- this is not the user_id in the app
      amount: Amount.default,
      description: "BigMoney Membership - #{current_user.email}",
      currency: 'usd')

    current_user.update_attributes(role: "premium")

    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to invest again."
    redirect_to root_path#user_path(current_user)

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This rescue block catches and displays those errors.
    rescue Stripe::CardError => e 
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def downgrade_user
    current_user.update_attributes(role: "standard")
    flash[:error] = "After you downgrade your private wikis will be public"
    redirect_to :back
  end

end



class Amount

  def self.default
    1500
  end

  def self.downgrade
    0
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def create
    user = User.find_by(email: params[:email])
    wiki = Wiki.find(params[:wiki_id])

    if !user
      flash[:error] = "There is no user by that email address: #{params[:email]}"
    elsif Collaborator.create(user: user, wiki: wiki)
      flash[:notice] = "Collaborator added"
    else
      flash[:error] = "Something went wrong"
    end
    redirect_to :back
  end

  def destroy
    collaborator = Collaborator.find(params[:id])
    wiki = Wiki.find(params[:wiki_id])

    if collaborator.destroy
      flash[:notice] = "Collaborator removed"
    else
      flash[:error] = "Remove collaborator failed"
    end
    redirect_to :back
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end

  def index
  end
  
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :find_wiki, only: [:show, :edit, :update, :destroy]

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user_id = current_user.id
    authorize @wiki
    
    if @wiki.save
      flash[:notice] = "Your wiki has been saved."
      redirect_to @wiki
    else
      flash[:error] = "Something went wrong."
      render :new
    end
  end

  def edit
    @collaborators = @wiki.collaborators
    @new_collaborator = Collaborator.new
    #authorize @wiki
  end

  def update
    #@wiki.user_id = current_user
    authorize @wiki
    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki is updated"
      redirect_to @wiki
    else 
      flash[:error] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy

    if @wiki.destroy
      flash[:notice] = "Wiki deleted successfully"
      redirect_to wikis_path
    else
      flash[:error] = "Something went wrong"
      render :show
    end
  end

  private

  def find_wiki
    @wiki = Wiki.find(params[:id])
  end

  def wiki_params
    params.require(:wiki).permit(:body, :title, :application, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end


end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<h2>Become a Premium User!</h2>
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>APSE Bug Tracker</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Bug Defects", wikis_path %></li>
      <% if current_user %>
        <li><%= link_to "Edit Account", edit_user_registration_path %></li>
      <% end %> 

      <div class="pull-right user-info">
        <% if current_user %>
            Greetings <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
            <%= link_to "Sign In", new_user_session_path %> or
            <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>

      <% if flash[:notice] %>
              <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                  <%= flash[:notice] %>
                </div>
            <% elsif flash[:error] %>
              <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:error] %>
              </div>
            <% elsif flash[:alert] %>
                <div class="alert alert-warning">
                <button type="button" class="close"
                data-dismiss="alert">&times;</button>
                <%= flash[:alert] %>
              </div>
              <% end %>


  <%= yield %>
  </div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>What is the NSC APSE Team's Bug Tracker</h1>
<p>This web tool is needed to assist the APSE Team with Development Bug Tracking across all applications at NSC.</p>

app/views/welcome/index.html.erb
<h1>APSE Team Bug Tracking</h1>
<p>This tool is used for tracking any bug defects and respective workarounds that are reported for each application within National Student Clearinghouse.</p>

app/views/wikis/_collaborator.html.erb
<p>
  <%= form_for [@wiki, collaborator], method: :delete do |f| %>
    <%= collaborator.user.email %>
    <%= f.submit "Remove" %>
  <% end %>
</p>

app/views/wikis/_new_collaborator.html.erb
<p>
  <%= form_for [@wiki, collaborator], {controller: "collaborators", action: "create"} do |f| %>
    <%= f.label :email %>
    <%= text_field_tag :email %>
    <%= f.submit "Add" %>
  <% end %>
</p>

app/views/wikis/edit.html.erb
<h1>Edit Bug Defect</h1>

<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>

  <div class="form-group">
    <%= f.label :application %>
    <%= f.text_field :application, class: 'form-control', placeholder: "Application affected" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 33, class: 'form-control', placeholder: "Place your wiki entry" %>
  </div>


  <% if current_user.role != 'standard' %>
   <div class="form-group">
    <%# label_tag(:private, "This wiki is private") %>
     <%= f.label :private %>
     <%= f.check_box :private %>
   </div>
  <% end %>

  <div class="form-group">
  <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>


   <% unless @wiki.public? %> 
    <h2>Collaborators</h2>
    <%= render partial: 'new_collaborator', locals: {collaborator: @new_collaborator} %>
    <%= render partial: 'collaborator', collection: @collaborators %>
   <% end %>

app/views/wikis/index.html.erb
<h1>List of Bug Defects</h1>
<table class="table">
  <tr> 
    <th colspan="0">
      <h2>Defects</h2>
    </th>  
  </tr>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Application</th>
    <th>Link</th>
    <th>Opened by</th>
  </tr>
  <% unless @wikis.nil? %>
    <% @wikis.each do |wiki| %> 
      <tr>
          <td><%= wiki.title %></td>
          <td><%= wiki.body %></td>
          <td><%= wiki.application %></td>
          <td><%= link_to wiki.title, wiki_path(wiki)%></td>
          <td><%= wiki.user.email if wiki.user %></td>
      </tr>
    <% end %>
    <% end %>
</table>

app/views/wikis/new.html.erb
<h1>New Bug Defect</h1>


  <div class="form-group">
    <%= form_for @wiki do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter defect title" %>
  </div>

  <div class="form-group">
      <%= f.label :application %>
      <%= f.text_field :application, class: 'form-control', placeholder: "Application affected" %>
  </div>

  <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 33, class: 'form-control', placeholder: "Place your defect entry"%>
  </div>

   
   <div class="form-group">
      <% if current_user.can_make_private_wiki? %>
        <%= f.label :private, class: "checkbox" %>
        <%= f.check_box :private %>
      <% end %>
      
   </div> 



  <div class="form-group">
    <%= f.submit  "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/wikis/show.html.erb
<h1><%= markdown_to_html @wiki.title %></h1>

<% if policy(@wiki).edit? %>
<%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
<% end %>

<% if policy(@wiki).destroy? %>
<%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete?'} %> 
<% end %>

<p><%= markdown_to_html @wiki.body %></p>